
package com.deadwingg.ws.soapserver.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.deadwingg.ws.soapserver.ObjectFactory;
import com.deadwingg.ws.soapserver.Producto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductoWSService", targetNamespace = "http://soapserver.ws.deadwingg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductoWSService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcular", targetNamespace = "http://soapserver.ws.deadwingg.com/", className = "com.deadwingg.ws.soapserver.Calcular")
    @ResponseWrapper(localName = "calcularResponse", targetNamespace = "http://soapserver.ws.deadwingg.com/", className = "com.deadwingg.ws.soapserver.CalcularResponse")
    @Action(input = "http://soapserver.ws.deadwingg.com/ProductoWSService/calcularRequest", output = "http://soapserver.ws.deadwingg.com/ProductoWSService/calcularResponse")
    public Double calcular(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.deadwingg.ws.soapserver.Producto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducto", targetNamespace = "http://soapserver.ws.deadwingg.com/", className = "com.deadwingg.ws.soapserver.GetProducto")
    @ResponseWrapper(localName = "getProductoResponse", targetNamespace = "http://soapserver.ws.deadwingg.com/", className = "com.deadwingg.ws.soapserver.GetProductoResponse")
    @Action(input = "http://soapserver.ws.deadwingg.com/ProductoWSService/getProductoRequest", output = "http://soapserver.ws.deadwingg.com/ProductoWSService/getProductoResponse")
    public Producto getProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
